project:
  type: book
  output-dir: docs
  resources:
    - ref/
    - css/

book:
  title: "情報関連"
  chapters:
    - index.qmd
    - 01_手芸クラフト.qmd
    - 02_武器クラフト.qmd
    - 03_受注場所.qmd
    - 04_組織関連.qmd
    
bibliography: ref/references.bib

format:
  html:
    embed-resources: true
    lightbox: true
    toc: true
    toc-depth: 2
    number-sections: true
    number-depth: 2
    code-line-numbers: false
    code-copy: true
    code-fold: true
    theme: [default, css/custom.scss]
    reference-location: margin
    citation-location: margin
    fig-align: center
    fig-cap-location: bottom
    tbl-cap-location: top
    df-print: paged
    lang: ja
    mermaid:
      theme: default
language:
  title-block-author-single: "作成者"
  title-block-author-plural: "作成者"
  title-block-published: "作成日"
  section-title-appendices: "付録"
crossref:
  fig-title: "図"
  tbl-title: "表"
  eq-title: "式"
  sec-prefix: "節"
  fig-prefix: "図"
  tbl-prefix: "表"
  eq-prefix: "式"
  ref-hyperlink: true
execute:
  echo: false
  cache: false
  freeze: false
editor:
  render-on-save: true
